name: Build and Push Docker Image to ghcr.io

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Triggers the workflow on pull requests targeting the main branch
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up QEMU for multi-platform builds (optional)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      # 5. Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .  # Path to the build context
          push: true
          tags: ghcr.io/${{ secrets.OWNER }}/${{ secrets.IMAGE_NAME }}:temurin-21
          # You can add multiple tags if needed
          # tags: |
          #   ghcr.io/${{ secrets.OWNER }}/${{ secrets.IMAGE_NAME }}:temurin-21
          #   ghcr.io/${{ secrets.OWNER }}/${{ secrets.IMAGE_NAME }}:latest

      # 6. (Optional) Log out from GitHub Container Registry
      - name: Log out from ghcr.io
        run: docker logout ghcr.io
